# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
workspace 'Shopr'

target 'Shopr' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Shopr
    pod "CryptoSwift"
    pod 'SwiftHTTP', '~> 2.0.0'
    pod 'Alamofire', '~> 4.0'
    pod 'SideMenuController'
end

